LogstashBuildWrapper: fix for use pipeline DSL
Fix issue:

    java.lang.UnsupportedOperationException: no known implementation of class jenkins.tasks.SimpleBuildWrapper is named LogstashBuildWrapper

When used thus:

wrap([$class: 'LogstashBuildWrapper']) {
    // some block
}